# Generated by Django 4.2.4 on 2023-08-23 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название букета')),
                ('composition', models.TextField(verbose_name='Состав букета')),
                ('price', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Цена букета')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bouquet_images/', verbose_name='Фото букета')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время создания заказа')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bouquet', to='flower_shop_site.bouquet', verbose_name='Заказанный букет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('delivery_time', models.CharField(choices=[('Как можно скорее', 'Как можно скорее'), ('с 10:00 до 12:00', 'с 10:00 до 12:00'), ('с 12:00 до 14:00', 'с 12:00 до 14:00'), ('с 14:00 до 16:00', 'с 14:00 до 16:00'), ('с 16:00 до 18:00', 'с 16:00 до 18:00'), ('с 18:00 до 20:00', 'с 18:00 до 20:00')], max_length=16, verbose_name='Предпочитаемое время доставки')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order', to='flower_shop_site.order', verbose_name='Заказ для доставки')),
            ],
            options={
                'verbose_name': 'Заказ на доставку',
                'verbose_name_plural': 'Заказы на доставку',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='flower_shop_site.tag', verbose_name='Тег'),
        ),
    ]
