# Generated by Django 4.2.4 on 2023-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_site', '0002_order_address_order_client_name_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено сообщение консультанту'),
        ),
    ]
