# Generated by Django 4.2.4 on 2023-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_site', '0005_bouquet_size_bouquet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TextField(default='Тут должно быть описание букета', verbose_name='Описание букета'),
        ),
    ]
